### ISSUE TITLE
--indent options allow inserting grammar breaking strings

### ISSUE THREAD

**Issue by hoostus** [SEIAROTg/autobean-format#1]
```
autobean-format --indent 2 my.beancount

lark.exceptions.UnexpectedToken: Unexpected token Token('NUMBER', '2') at line 1, column 1.

```

The indent option seems to allow arbitrary strings, which then results in breaking the parser. It should probably check the the string is only spaces and/or tabs. Or maybe just make it --indent-spaces=4 or --indent-tabs=1 since I think those are the only two realistic options?

**Comment by SEIAROTg** [comment]
Validation now added in e7eaa2499c8ce3afb36f6def394c4f7982ed0be3.

> Or maybe just make it --indent-spaces=4 or --indent-tabs=1

I was actually trying to save a bit of boring code validating their mutual exclusivity, and allow crazy people to specify `--indent=$'  \t'`. 😛
