### ISSUE TITLE
Accept stdin?

### ISSUE THREAD

**Issue by redstreet** [SEIAROTg/autobean-format#4]
If `autobean-format` could accept `stdin`, it can start being incorporated into editors like vim and emacs. I imagine it's trivial to add support for it. Happy to send a PR at some point if needed.

Thanks for making and sharing this! The simplicity and reliability rock!

**Comment by SEIAROTg** [comment]
Sounds good and PR welcomed!

**Comment by SEIAROTg** [comment]
Fixed in #5.
