### ISSUE TITLE
Ubuntu doesn't like python 3.11 (yet) but this plugin requires that.

### ISSUE THREAD

**Issue by berkes** [SEIAROTg/autobean-format#7]
Is it possible to downgrade the python version requirements?

This plugin needs 3.11, which on current Ubuntu isn't available. And upgrading breaks the OS (well, desktop, GTK and such).

I'd imagine the requirement for 3.11 isn't in features needed or used, is it? Maybe the dependency constraint can be downgraded without even changing the code? I'm not a python dev, so unable to help, sorry.

**Comment by SEIAROTg** [comment]
Fixed in 0d99868e6b5ff26b610540e26a195e9e5765d695.
